spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/gift?autoReconnect=true
    driver: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:QazWsx123.}
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  sql:
    init:
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
management:
  endpoints:
    web:
      exposure:
        include: "*"