CREATE TABLE user (
  id BIGINT  NOT NULL  IDENTITY,
  username VARCHAR(45)  NOT NULL,
  role VARCHAR(45)  NOT NULL,
  surname VARCHAR(45)  NOT NULL,
  middlename VARCHAR(45)  NOT NULL,
  email VARCHAR(45)  NOT NULL,
  PRIMARY KEY (id)
);

